window.DECK = {
  id: '03', title: 'Search results and read timestamps',
  label: 'Round 2 / one unresolved read-tracking rule', duration: 'about 2 minutes total',
  slides: [
    {title: 'A timestamp needs an exact content version', html: `<p><strong>Settled:</strong> track automatically, show net diffs by default, retain intermediate edits in history. No acknowledgement step. Peek can wait.</p><p>A timestamp answers “when did Alice see this?” A revision answers “which content did she receive?” Keep both at the object level.</p><pre><code>10:00:00  Alice starts receiving post 42, revision 7
10:00:01  Bob saves revision 8
10:00:02  Alice's output finishes</code></pre><p>If the next query asks only for edits after 10:00:02, it misses Bob's edit. Recording revision 7 avoids that race. Time alone requires a precisely defined snapshot boundary and tie handling.</p>`},
    {title: 'Search results should participate in tracking', html: `<p>My earlier blanket exclusion of search was wrong. The remaining distinction is how much of the object the result contains.</p><table><tr><th>Search result delivered</th><th>Proposed automatic update</th></tr><tr><td>Full post at revision 9</td><td>Observation time and diff baseline become current.</td></tr><tr><td>Complete net diff through revision 9</td><td>Same update.</td></tr><tr><td>Only the title or a snippet at revision 9</td><td>Observation time advances; diff baseline stays at 7.</td></tr></table><p>This uses one observation timestamp and one content baseline per object. It needs no per-field receipts. Objects omitted from the results receive no update.</p>`},
    {title: 'The real choice: does a snippet consume the body?', html: `<p>Suppose revision 9 already contains an important warning. Search returns only its title. Tomorrow revision 10 changes one unrelated line.</p><p><strong>Mark revision 9 fully read:</strong> tomorrow's diff covers 9–10. The undisplayed warning can disappear from ordinary catch-up. This is reasonable only if “read” means encountered, irrespective of omitted content.</p><p><strong>Keep the full-content baseline:</strong> tomorrow's diff covers 7–10, including that warning. Some previously displayed material may repeat.</p><p class="callout">I recommend the second rule, while recording every displayed search result's observation time. This boundary is still a proposal; your feedback did not settle it.</p>`}
  ]
};
